# Age
age1850_xpath = '//button[contains(@class,"ageselect_1850")]'

# Start/Finish
start_id = 'startTest'
finish_xpath = '//div[@id="question_34"]/div/div/button[contains(@class,"questionFinish")]'


# Tests
ex1_a_xpath = '//div[@id="question_0"]/div/div/div[@data-answerid="0"]'
ex2_b_xpath = '//div[@id="question_1"]/div/div/div[@data-answerid="1"]'
ex3_c_xpath = '//div[@id="question_2"]/div/div/div[@data-answerid="2"]'
ex4_d_xpath = '//div[@id="question_3"]/div/div/div[@data-answerid="3"]'
ex5_e_xpath = '//div[@id="question_4"]/div/div/div[@data-answerid="4"]'
ex6_f_xpath = '//div[@id="question_5"]/div/div/div[@data-answerid="5"]'
ex7_a_xpath = '//div[@id="question_6"]/div/div/div[@data-answerid="0"]'
ex8_b_xpath = '//div[@id="question_7"]/div/div/div[@data-answerid="1"]'
ex9_c_xpath = '//div[@id="question_8"]/div/div/div[@data-answerid="2"]'
ex10_d_xpath = '//div[@id="question_9"]/div/div/div[@data-answerid="3"]'
ex11_e_xpath = '//div[@id="question_10"]/div/div/div[@data-answerid="4"]'
ex12_f_xpath = '//div[@id="question_11"]/div/div/div[@data-answerid="5"]'
ex13_a_xpath = '//div[@id="question_12"]/div/div/div[@data-answerid="0"]'
ex14_b_xpath = '//div[@id="question_13"]/div/div/div[@data-answerid="1"]'
ex15_c_xpath = '//div[@id="question_14"]/div/div/div[@data-answerid="2"]'
ex16_d_xpath = '//div[@id="question_15"]/div/div/div[@data-answerid="3"]'
ex17_e_xpath = '//div[@id="question_16"]/div/div/div[@data-answerid="4"]'
ex18_f_xpath = '//div[@id="question_17"]/div/div/div[@data-answerid="5"]'
ex19_a_xpath = '//div[@id="question_18"]/div/div/div[@data-answerid="0"]'
ex20_b_xpath = '//div[@id="question_19"]/div/div/div[@data-answerid="1"]'
ex21_c_xpath = '//div[@id="question_20"]/div/div/div[@data-answerid="2"]'
ex22_d_xpath = '//div[@id="question_21"]/div/div/div[@data-answerid="3"]'
ex23_e_xpath = '//div[@id="question_22"]/div/div/div[@data-answerid="4"]'
ex24_f_xpath = '//div[@id="question_23"]/div/div/div[@data-answerid="5"]'
ex25_a_xpath = '//div[@id="question_24"]/div/div/div[@data-answerid="0"]'
ex26_b_xpath = '//div[@id="question_25"]/div/div/div[@data-answerid="1"]'
ex27_c_xpath = '//div[@id="question_26"]/div/div/div[@data-answerid="2"]'
ex28_d_xpath = '//div[@id="question_27"]/div/div/div[@data-answerid="3"]'
ex29_e_xpath = '//div[@id="question_28"]/div/div/div[@data-answerid="4"]'
ex30_f_xpath = '//div[@id="question_29"]/div/div/div[@data-answerid="5"]'
ex31_a_xpath = '//div[@id="question_30"]/div/div/div[@data-answerid="0"]'
ex32_b_xpath = '//div[@id="question_31"]/div/div/div[@data-answerid="1"]'
ex33_c_xpath = '//div[@id="question_32"]/div/div/div[@data-answerid="2"]'
ex34_d_xpath = '//div[@id="question_33"]/div/div/div[@data-answerid="3"]'
ex35_e_xpath = '//div[@id="question_34"]/div/div/div[@data-answerid="4"]'

# Done
done_already_xpath = '//div[@id="endTestDialog"]/div/div/div/button[contains(@class, "btn-danger")]'